### ISSUE TITLE
Skopeo version needs push

### ISSUE THREAD

**Issue by shoeper** [xelalexv/dregsy#7] opened 2019-05-13 14:44 UTC
Currently used version uses and old version using ubuntu 17.10. Build fails on git update due to that.

**Comment by xelalexv** [comment] 2019-05-13 17:42
Thanks for reporting this! This [_Skopeo_ issue](https://github.com/containers/skopeo/issues/621) is the root cause of the problem. It has already been fixed in _Skopeo's_ `master` (Ubuntu 18.10 is used now), but has not been officially released yet (latest release `v0.1.35` does not include this). I don't want to reference an unreleased state, so for the time being, we'll keep the version at `v0.1.32`. I modified _dregsy's_ Makefile to patch _Skopeo's_ `Dockerfile.build` on the fly during the build to use Ubuntu 18.10. Once the next _Skopeo_ release is out, I'll upgrade to that. I'll keep this issue open as a reminder.

**Comment by shoeper** [comment] 2019-05-13 17:45
Ok, thanks. I fixed it on my automated build by using skopeo master for now.

**Comment by shoeper** [comment] 2019-05-17 14:55
I've mentioned the issue with the release at https://github.com/containers/skopeo/issues/648

**Comment by xelalexv** [comment] 2020-05-26 14:34
This will become obsolete once #14 is done.

**Comment by xelalexv** [comment] 2020-06-15 09:59
obsolete with PR #15

**Closed by xelalexv** 2020-06-15 09:59 UTC
