### ISSUE TITLE
attempt to sync nexus docker registry

### ISSUE THREAD

**Issue by fidelina** [xelalexv/dregsy#18] opened 2020-07-28 18:10 UTC
I'm trying to synchronize docker registry, but I'm getting fail 
```
2020-07-27T16:10:11Z [INFO]
2020-07-27T16:10:41Z [INFO] task 'task1' fired too soon, skipping
2020-07-27T16:10:41Z [INFO] waiting for next sync task...
2020-07-27T16:10:41Z [INFO]
2020-07-27T16:11:41Z [INFO] syncing task 'task1': '10.10.10.10:5000' --> '10.20.20.20:5000'
2020-07-27T16:11:41Z [INFO] mapping '/dev/app' to '/dev/app'
2020-07-27T16:11:41Z [INFO] pulling source image '10.10.10.10:5000/dev/app'
64: Pulling from dev/app
Digest: sha256:033952a79c057676881dd67340e92dab53e6385564575a3d3f9d99a4cece3b30
65: Pulling from dev/app
Digest: sha256:d383efc0a584ca9424a1282028ae549272a4cdad38e26bf20709e8d834ff3010
72: Pulling from dev/app
Digest: sha256:e0ad897b05da6a4829af49ee4f71e10d06ed4710b35f3cb883a0380bdad33c50
74: Pulling from dev/app
Digest: sha256:53008ada6c3dfa96ecb96b6c51f43809791ea5cee83d8ef1fad3c8a24cc20b05
Status: Image is up to date for 10.10.10.10:5000/dev/app
2020-07-27T16:11:41Z [INFO] relevant tags
2020-07-27T16:11:41Z [ERROR] error listing all tags of source image '10.10.10.10:5000/dev/app': malformed image ref: invalid reference format
2020-07-27T16:11:41Z [ERROR] error pushing target image: An image does not exist locally with the tag: 10.20.20.20:5000/dev/app
2020-07-27T16:11:41Z [INFO] setting tags for target image '10.20.20.20:5000/dev/app'
2020-07-27T16:11:41Z [INFO] pushing target image '10.20.20.20:5000/dev/app'
The push refers to repository [10.20.20.20:5000/dev/app]
2020-07-27T16:11:41Z [INFO]
2020-07-27T16:11:41Z [INFO] waiting for next sync task...
2020-07-27T16:11:41Z [INFO]
```
_________________

```


# relay type, either 'skopeo' or 'docker'
relay: docker

docker:
  # Docker host to use as the relay
  dockerhost: unix:///var/run/docker.sock
  # Docker API version to use, defaults to 1.24
  api-version: 1.24

# list of sync tasks
tasks:

  - name: task1 # required

    # interval in seconds at which the task should be run; when omitted,
    # the task is only run once at start-up
    interval: 60

    # determines whether for this task, more verbose output should be
    # produced; defaults to false when omitted
    verbose: true

    # 'source' and 'target' are both required and describe the source and
    # target registries for this task:
    #  - 'registry' points to the server; required
    #  - 'auth' contains the base64 encoded credentials for the registry
    #    in JSON form {"username": "...", "password": "..."}
    #  - 'auth-refresh' specifies an interval for automatic retrieval of
    #    credentials; only for AWS ECR (see below)
    #  - 'skip-tls-verify' determines whether to skip TLS verification for the
    #    registry server (only for 'skopeo', see note below); defaults to false
    source:
      registry: 10.10.10.10:5000
      auth: YYYYWRtaW46TmNZMTMwcnI=
    #  skip-tls-verify: true
    target:
      registry: 10.20.20.20:5000
      auth: YYYYWRtaW46TmNZMTMwcnI=
    #  skip-tls-verify: true

    # 'mappings' is a list of 'from':'to' pairs that define mappings of image
    # paths in the source registry to paths in the destination; 'from' is
    # required, while 'to' can be dropped if the path should remain the same as
    # 'from'. Additionally, the tags being synced for a mapping can be limited
    # by providing a 'tags' list. When omitted, all image tags are synced.
    mappings:
      - from: dev/app 
```

______________

```
docker run --privileged --rm -v /var/run/docker.sock:/var/run/docker.sock dregsy:0.3.0
```

**Comment by fidelina** [comment] 2020-07-29 07:03
I haven't problem on dregsy:0.2.0

**Comment by xelalexv** [comment] 2020-07-29 08:44
Thanks for reporting this! I've just tried to reproduce the issue. I'm running two instances of Nexus (3.14.0) locally via Docker. Using dregsy, I first synced `library/alpine` from DockerHub to the first Nexus, then synced from that to the second Nexus, no problems. I'll investigate further. Are your registries both Nexus? Are they running HTTPS?

**Comment by xelalexv** [comment] 2020-07-29 09:32
I may be onto something. When dregsy determines available tags for an image while using the Docker relay, it needs to list local images and then filters out what it's interested in (see [here](https://github.com/xelalexv/dregsy/blob/master/internal/pkg/relays/docker/docker.go#L176)). This logic has changed since version `0.2.0`. It seems that the reference to one of the local images in your environment causes an error during the filtering. I added more info to the error message and created branch `issue18` and pushed an accompanying image to DockerHub (`xelalex/dregsy:issue18`). Could you try with that and post output here?

**Comment by fidelina** [comment] 2020-07-29 12:37
1) I deleted all docker images.
````
docker rm -vf $(docker ps -aq)
docker rmi -f $(docker images -aq)
docker volume prune -f
```
2) I ran dregsy as docker relay and as skopeo relay dregsy:issue18. It's work

**Comment by xelalexv** [comment] 2020-07-29 13:12
That confirms my analysis. It would have been good though to know which particular reference caused the error. I can imagine that for example an intermediate build image could cause trouble. Anyway, I'll merge the additional log info into master, so we have more info next time we run into a similar situation. Can we close this issue?

**Comment by fidelina** [comment] 2020-07-29 18:42
Thanks you very much for your work!

**Closed** 2020-07-30 07:32 UTC
